export const SET_PROPERTY = "SET_PROPERTY";
export const SET_TRAVELLER = "SET_TRAVELLER";
export const SET_OWNER = "SET_OWNER";
export const SET_SEARCH_QUERY = "SET_SEARCH_QUERY";
export const SET_SEARCH_RESULTS = "SET_SEARCH_RESULTS";
export const SET_CURRENT_PROPERTY = "SET_CURRENT_PROPERTY";
export const TRAVELLER_LOGOUT = "TRAVELLER_LOGOUT";
export const OWNER_LOGOUT = "OWNER_LOGOUT";